karyotype = karyotype.txt

############################
## IDEOGRAM (outer genome rings)
############################
<ideogram>

<spacing>
default = 0.03r
</spacing>

radius       = 0.80r
thickness    = 30p
fill         = yes
show_label   = yes
label_size   = 28
label_radius = dims(ideogram,radius_outer) + 0.05r

</ideogram>

############################
## LINKS (genome alignments)
############################
<links>
<link>
file          = links.filtered.txt
radius        = 0.78r
bezier_radius = 0.1r
thickness     = 2
color         = black_a4
</link>
</links>

############################
## OUTPUT IMAGE
############################
<image>
dir   = .
file  = circos_comamonas.png
png   = yes
svg   = yes
radius = 1500p
</image>

############################
## DEFAULT SETTINGS
############################
<<include etc/colors_fonts_patterns.conf>>
<<include etc/housekeeping.conf>>